spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  rabbitmq-channel:
    exchangeName: evento.topic
    queueName: notificacao
    routingKey: notificacao.email
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: ms-reservas
      authentication-database: admin

server:
  port: 8081

quartos-service:
  url: http://localhost:8080/api/v1/quartos

servicos-opcionais-service:
  url: http://localhost:8085/servicos-opcionais

cliente-service:
  url: http://localhost:8080/v1/clientes
