server:
  port: 8080
spring:
  application:
    name: micro-reservas
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  rabbitmq-channel:
    exchangeName: evento.direct
    queueName: notificacao.email
    routingKey: notificacao.email