version: '3'

services:
  ms-servicos:
    container_name: ms-servicos
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbServicos
    ports:
      - 5432:5432