spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userms-mysql
    username: dev
    password: fiap
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    path: ./var/log


api:
  security:
    token:
      secret: "ea527c405f047dd870c2f31680499293c011cc4280f5b2a39e3fde6885682161"

nome.required: "Campo Nome é obrigatório."
sobrenome.required: "Campo Sobrenome é obrigatório."
cpf.required: "Campo CPF é obrigatório."
passaporte.required: "Campo Passaporte é obrigatório."
dataDeAniversario.required: "Campo Data de Aniversário é obrigatório."
genero.required: "Campo Gênero é obrigatório."
endereco.required: "Campo Endereço é obrigatório."
paisDeOrigem.required: "Campo País de Origem é obrigatório."
nivel.required: "Campo Nível é obrigatório."
email.required: "Campo E-mail é obrigatório."
usuario.required: "Campo Usuário é obrigatório."
senha.required: "Campo Senha é obrigatório."
telefone.required: "Campo Telefone é obrigatório."
